version: '3.4'

x-common-variables: &common-variables
  DEBUG: True
  ENVIRONMENT: production
  SERVICE_NAME: sale-notify
  POSTGRES_NAME: ${POSTGRES_NAME}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_POOL_MIN_SIZE: 1
  POSTGRES_POOL_MAX_SIZE: 10
  TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_URL: redis://redis:6379
  SELF_URL: http://app:${API_PORT}

services:
  db:
    image: postgres:15.4
    environment:
      <<: *common-variables
    restart: always
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data

  migrations:
    image: sale_service
    build:
      context: ../
      dockerfile: devops/Dockerfile
    environment:
      <<: *common-variables
    working_dir: /
    command: aerich upgrade

  app:
    image: sale_service
    environment:
      <<: *common-variables
    command: uvicorn main:app --host 0.0.0.0 --port ${API_PORT} --reload
    depends_on:
      - migrations
    restart: always

  bot:
    image: sale_service
    environment:
      <<: *common-variables
    command: python bot/main.py
    depends_on:
      - app
    restart: always

  beat:
    image: sale_service
    environment:
      <<: *common-variables
    command: celery -A broker:celery_app beat
    depends_on:
      - app
    restart: always

  worker:
    image: sale_service
    environment:
      <<: *common-variables
    command: celery -A broker:celery_app worker --concurrency 1
    depends_on:
      - app
    restart: always

volumes:
  db:
    driver: local
  redis:
    driver: local